name: enterprise_dw
version: '1.0'
config-version: 2
profile: enterprise_dw

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  enterprise_dw:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  enterprise_dw:
    raw:
      +schema: raw
      +quote_columns: false
    etl_outputs:
      +schema: analytics
      +quote_columns: false
